"""initial schema

Revision ID: e97f8590d00c
Revises:
Create Date: 2026-09-22 00:34:22.900474
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "e97f8590d00c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("before_json", sa.JSON(), nullable=True),
        sa.Column("after_json", sa.JSON(), nullable=True),
        sa.Column("occurred_at", sa.String(length=32), nullable=False),
        sa.Column("previous_hash", sa.String(length=64), nullable=False),
        sa.Column("event_hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_hash"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_events_entity_id"), ["entity_id"], unique=False)

    op.create_table(
        "data_sources",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("license_url", sa.String(length=500), nullable=False),
        sa.Column("license_name", sa.String(length=200), nullable=False),
        sa.Column("retrieval_date", sa.String(length=10), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.Column("intended_use", sa.Text(), nullable=False),
        sa.Column("limitations", sa.Text(), nullable=False),
        sa.Column("doc_path", sa.String(length=500), nullable=False),
        sa.Column("license_confirmed_by", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "data_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("as_of_date", sa.String(length=10), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("schema_hash", sa.String(length=64), nullable=False),
        sa.Column("quality_status", sa.String(length=16), nullable=False),
        sa.Column("quality_json", sa.JSON(), nullable=False),
        sa.Column("profile_json", sa.JSON(), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "training_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("git_sha", sa.String(length=64), nullable=True),
        sa.Column("random_seed", sa.Integer(), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("artifact_dir", sa.String(length=500), nullable=True),
        sa.Column("artifacts_json", sa.JSON(), nullable=False),
        sa.Column("metrics_json", sa.JSON(), nullable=False),
        sa.Column("hypothesis_tests_json", sa.JSON(), nullable=False),
        sa.Column("baseline_distributions_json", sa.JSON(), nullable=False),
        sa.Column("requested_by", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["data_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "model_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("semantic_version", sa.String(length=64), nullable=False),
        sa.Column("training_run_id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("artifact_uri", sa.String(length=500), nullable=False),
        sa.Column("model_type", sa.String(length=32), nullable=False),
        sa.Column("owner", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("retirement_reason", sa.Text(), nullable=True),
        sa.Column("measured_json", sa.JSON(), nullable=False),
        sa.Column("narrative_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["training_run_id"],
            ["training_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("semantic_version"),
    )
    op.create_table(
        "approval_decisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("model_version_id", sa.String(length=36), nullable=False),
        sa.Column("reviewer_id", sa.String(length=64), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("decided_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("approval_decisions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_approval_decisions_model_version_id"), ["model_version_id"], unique=False)

    op.create_table(
        "controls",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("model_version_id", sa.String(length=36), nullable=False),
        sa.Column("control_name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("owner", sa.String(length=64), nullable=False),
        sa.Column("frequency", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("evidence_uri", sa.String(length=500), nullable=False),
        sa.Column("test_evidence", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("controls", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_controls_model_version_id"), ["model_version_id"], unique=False)

    op.create_table(
        "copilot_queries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("model_version_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("cited_document_ids", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("question_length", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("copilot_queries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_copilot_queries_model_version_id"), ["model_version_id"], unique=False)

    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("model_version_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("path", sa.String(length=500), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_version_id", "type", name="uq_document_version_type"),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_documents_model_version_id"), ["model_version_id"], unique=False)

    op.create_table(
        "metric_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("model_version_id", sa.String(length=36), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("metric_name", sa.String(length=64), nullable=False),
        sa.Column("metric_value", sa.Float(), nullable=False),
        sa.Column("lower_ci", sa.Float(), nullable=True),
        sa.Column("upper_ci", sa.Float(), nullable=True),
        sa.Column("batch_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("metric_results", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_metric_results_model_version_id"), ["model_version_id"], unique=False)

    op.create_table(
        "monitoring_batches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("model_version_id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("as_of_date", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("labels_available", sa.Boolean(), nullable=False),
        sa.Column("results_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["data_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("monitoring_batches", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_monitoring_batches_model_version_id"), ["model_version_id"], unique=False)

    op.create_table(
        "readiness_checks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("model_version_id", sa.String(length=36), nullable=False),
        sa.Column("check_name", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("missing_json", sa.JSON(), nullable=False),
        sa.Column("evidence_json", sa.JSON(), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("readiness_checks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_readiness_checks_model_version_id"), ["model_version_id"], unique=False)

    op.create_table(
        "validation_artifacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("model_version_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_version_id", "name", name="uq_artifact_version_name"),
    )
    with op.batch_alter_table("validation_artifacts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_validation_artifacts_model_version_id"), ["model_version_id"], unique=False
        )

    op.create_table(
        "alerts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("monitoring_batch_id", sa.String(length=36), nullable=False),
        sa.Column("model_version_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("detail_json", sa.JSON(), nullable=False),
        sa.Column("owner", sa.String(length=64), nullable=False),
        sa.Column("due_date", sa.String(length=10), nullable=False),
        sa.Column("investigation_note", sa.Text(), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["monitoring_batch_id"],
            ["monitoring_batches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_alerts_model_version_id"), ["model_version_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_monitoring_batch_id"), ["monitoring_batch_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alerts_monitoring_batch_id"))
        batch_op.drop_index(batch_op.f("ix_alerts_model_version_id"))

    op.drop_table("alerts")
    with op.batch_alter_table("validation_artifacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_validation_artifacts_model_version_id"))

    op.drop_table("validation_artifacts")
    with op.batch_alter_table("readiness_checks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_readiness_checks_model_version_id"))

    op.drop_table("readiness_checks")
    with op.batch_alter_table("monitoring_batches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_monitoring_batches_model_version_id"))

    op.drop_table("monitoring_batches")
    with op.batch_alter_table("metric_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_metric_results_model_version_id"))

    op.drop_table("metric_results")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_model_version_id"))

    op.drop_table("documents")
    with op.batch_alter_table("copilot_queries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_copilot_queries_model_version_id"))

    op.drop_table("copilot_queries")
    with op.batch_alter_table("controls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_controls_model_version_id"))

    op.drop_table("controls")
    with op.batch_alter_table("approval_decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approval_decisions_model_version_id"))

    op.drop_table("approval_decisions")
    op.drop_table("model_versions")
    op.drop_table("training_runs")
    op.drop_table("data_snapshots")
    op.drop_table("users")
    op.drop_table("data_sources")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_entity_id"))

    op.drop_table("audit_events")
    # ### end Alembic commands ###
